CREATE USER 'gsbfrais'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'gsbfrais'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'gsbfrais'@'localhost' IDENTIFIED BY PASSWORD '*63A399F2ACF69593CA20DA9F8AD556D082F90778';
